// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfzcrx6QgC8w69oVIfbZmI5vYGKXX0m_k',
    appId: '1:101585046920:web:282abf34ac1dd7d17cbe3d',
    messagingSenderId: '101585046920',
    projectId: 'educational-platform-16729',
    authDomain: 'educational-platform-16729.firebaseapp.com',
    storageBucket: 'educational-platform-16729.firebasestorage.app',
    measurementId: 'G-5E7L71DCL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtX1vxQsXUC6YOagd2HlSSGeJKJKigc8c',
    appId: '1:101585046920:android:f12e5cd8827ff23e7cbe3d',
    messagingSenderId: '101585046920',
    projectId: 'educational-platform-16729',
    storageBucket: 'educational-platform-16729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvjije9QxNRndD9XZonFQMXhnmIGdf8o',
    appId: '1:101585046920:ios:075c0b19838f77017cbe3d',
    messagingSenderId: '101585046920',
    projectId: 'educational-platform-16729',
    storageBucket: 'educational-platform-16729.firebasestorage.app',
    iosBundleId: 'com.example.educationalPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvjije9QxNRndD9XZonFQMXhnmIGdf8o',
    appId: '1:101585046920:ios:075c0b19838f77017cbe3d',
    messagingSenderId: '101585046920',
    projectId: 'educational-platform-16729',
    storageBucket: 'educational-platform-16729.firebasestorage.app',
    iosBundleId: 'com.example.educationalPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfzcrx6QgC8w69oVIfbZmI5vYGKXX0m_k',
    appId: '1:101585046920:web:394ae56088a357037cbe3d',
    messagingSenderId: '101585046920',
    projectId: 'educational-platform-16729',
    authDomain: 'educational-platform-16729.firebaseapp.com',
    storageBucket: 'educational-platform-16729.firebasestorage.app',
    measurementId: 'G-ZG97DQMKT4',
  );
}
