"""
✨ `Resource_KeyOutput` returns the primary key fields of table type `Resource`.

It has the same format as `Resource_Key`, but is only used as mutation return value.
"""
scalar Resource_KeyOutput
"""
✨ `Review_KeyOutput` returns the primary key fields of table type `Review`.

It has the same format as `Review_Key`, but is only used as mutation return value.
"""
scalar Review_KeyOutput
"""
✨ `Session_KeyOutput` returns the primary key fields of table type `Session`.

It has the same format as `Session_Key`, but is only used as mutation return value.
"""
scalar Session_KeyOutput
"""
✨ `Subject_KeyOutput` returns the primary key fields of table type `Subject`.

It has the same format as `Subject_Key`, but is only used as mutation return value.
"""
scalar Subject_KeyOutput
"""
✨ `TutorProfile_KeyOutput` returns the primary key fields of table type `TutorProfile`.

It has the same format as `TutorProfile_Key`, but is only used as mutation return value.
"""
scalar TutorProfile_KeyOutput
"""
✨ `TutorSubject_KeyOutput` returns the primary key fields of table type `TutorSubject`.

It has the same format as `TutorSubject_Key`, but is only used as mutation return value.
"""
scalar TutorSubject_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ Generated data input type for table 'Resource'. It includes all necessary fields for creating or upserting rows into table.
"""
input Resource_Data {
  """
  ✨ Generated from Field `Resource`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Resource`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Resource`.`subjectId` of type `UUID!`
  """
  subjectId: UUID
  """
  ✨ `_expr` server value variant of `subjectId` (✨ Generated from Field `Resource`.`subjectId` of type `UUID!`)
  """
  subjectId_expr: UUID_Expr
  """
  ✨ Generated from Field `Resource`.`uploaderId` of type `UUID!`
  """
  uploaderId: UUID
  """
  ✨ `_expr` server value variant of `uploaderId` (✨ Generated from Field `Resource`.`uploaderId` of type `UUID!`)
  """
  uploaderId_expr: UUID_Expr
  """
  ✨ Generated from Field `Resource`.`subject` of type `Subject!`
  """
  subject: Subject_Key
  """
  ✨ Generated from Field `Resource`.`uploader` of type `User!`
  """
  uploader: User_Key
  """
  ✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Resource`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Resource`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Resource`.`fileUrl` of type `String!`
  """
  fileUrl: String
  """
  ✨ `_expr` server value variant of `fileUrl` (✨ Generated from Field `Resource`.`fileUrl` of type `String!`)
  """
  fileUrl_expr: String_Expr
  """
  ✨ Generated from Field `Resource`.`resourceType` of type `String!`
  """
  resourceType: String
  """
  ✨ `_expr` server value variant of `resourceType` (✨ Generated from Field `Resource`.`resourceType` of type `String!`)
  """
  resourceType_expr: String_Expr
  """
  ✨ Generated from Field `Resource`.`tags` of type `[String]`
  """
  tags: [String!]
  """
  ✨ `_update` server value variant of `tags` (✨ Generated from Field `Resource`.`tags` of type `[String]`)
  """
  tags_update: [String_ListUpdate!]
  """
  ✨ Generated from Field `Resource`.`title` of type `String!`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Resource`.`title` of type `String!`)
  """
  title_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Resource'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Resource_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Resource_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Resource_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Resource_Filter!]
  """
  ✨ Generated from Field `Resource`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Resource`.`subjectId` of type `UUID!`
  """
  subjectId: UUID_Filter
  """
  ✨ Generated from Field `Resource`.`uploaderId` of type `UUID!`
  """
  uploaderId: UUID_Filter
  """
  ✨ Generated from Field `Resource`.`subject` of type `Subject!`
  """
  subject: Subject_Filter
  """
  ✨ Generated from Field `Resource`.`uploader` of type `User!`
  """
  uploader: User_Filter
  """
  ✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Resource`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Resource`.`fileUrl` of type `String!`
  """
  fileUrl: String_Filter
  """
  ✨ Generated from Field `Resource`.`resourceType` of type `String!`
  """
  resourceType: String_Filter
  """
  ✨ Generated from Field `Resource`.`tags` of type `[String]`
  """
  tags: String_ListFilter
  """
  ✨ Generated from Field `Resource`.`title` of type `String!`
  """
  title: String_Filter
}
"""
✨ Generated first-row input type for table 'Resource'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Resource_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Resource_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Resource_Filter
}
"""
✨ Generated having input type for table 'Resource'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Resource_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Resource_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Resource_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Resource_Having!]
  """
  ✨ Generated from Field `Resource`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`fileUrl_count` of type `Int!`
  """
  fileUrl_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`resourceType_count` of type `Int!`
  """
  resourceType_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`subjectId_count` of type `Int!`
  """
  subjectId_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`uploaderId_count` of type `Int!`
  """
  uploaderId_count: Int_Filter
  """
  ✨ Generated from Field `Resource`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Resource`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Resource'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Resource_Key {
  """
  ✨ Generated from Field `Resource`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Resource`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Resource'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Resource_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Resource_Filter
}
"""
✨ Generated order input type for table 'Resource'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Resource_Order {
  """
  ✨ Generated from Field `Resource`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Resource`.`subjectId` of type `UUID!`
  """
  subjectId: OrderDirection
  """
  ✨ Generated from Field `Resource`.`uploaderId` of type `UUID!`
  """
  uploaderId: OrderDirection
  """
  ✨ Generated from Field `Resource`.`subject` of type `Subject!`
  """
  subject: Subject_Order
  """
  ✨ Generated from Field `Resource`.`uploader` of type `User!`
  """
  uploader: User_Order
  """
  ✨ Generated from Field `Resource`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Resource`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Resource`.`fileUrl` of type `String!`
  """
  fileUrl: OrderDirection
  """
  ✨ Generated from Field `Resource`.`resourceType` of type `String!`
  """
  resourceType: OrderDirection
  """
  ✨ Generated from Field `Resource`.`title` of type `String!`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Resource`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`fileUrl_count` of type `Int!`
  """
  fileUrl_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`resourceType_count` of type `Int!`
  """
  resourceType_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`subjectId_count` of type `Int!`
  """
  subjectId_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`uploaderId_count` of type `Int!`
  """
  uploaderId_count: OrderDirection
  """
  ✨ Generated from Field `Resource`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Resource`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Review'. It includes all necessary fields for creating or upserting rows into table.
"""
input Review_Data {
  """
  ✨ Generated from Field `Review`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Review`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Review`.`sessionId` of type `UUID!`
  """
  sessionId: UUID
  """
  ✨ `_expr` server value variant of `sessionId` (✨ Generated from Field `Review`.`sessionId` of type `UUID!`)
  """
  sessionId_expr: UUID_Expr
  """
  ✨ Generated from Field `Review`.`studentId` of type `UUID!`
  """
  studentId: UUID
  """
  ✨ `_expr` server value variant of `studentId` (✨ Generated from Field `Review`.`studentId` of type `UUID!`)
  """
  studentId_expr: UUID_Expr
  """
  ✨ Generated from Field `Review`.`tutorId` of type `UUID!`
  """
  tutorId: UUID
  """
  ✨ `_expr` server value variant of `tutorId` (✨ Generated from Field `Review`.`tutorId` of type `UUID!`)
  """
  tutorId_expr: UUID_Expr
  """
  ✨ Generated from Field `Review`.`session` of type `Session!`
  """
  session: Session_Key
  """
  ✨ Generated from Field `Review`.`student` of type `User!`
  """
  student: User_Key
  """
  ✨ Generated from Field `Review`.`tutor` of type `User!`
  """
  tutor: User_Key
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: Int
  """
  ✨ `_expr` server value variant of `rating` (✨ Generated from Field `Review`.`rating` of type `Int!`)
  """
  rating_expr: Int_Expr
  """
  ✨ `_update` server value variant of `rating` (✨ Generated from Field `Review`.`rating` of type `Int!`)
  """
  rating_update: [Int_Update!]
  """
  ✨ Generated from Field `Review`.`reviewText` of type `String!`
  """
  reviewText: String
  """
  ✨ `_expr` server value variant of `reviewText` (✨ Generated from Field `Review`.`reviewText` of type `String!`)
  """
  reviewText_expr: String_Expr
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`)
  """
  updatedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Review'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Review_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Review_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Review_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Review_Filter!]
  """
  ✨ Generated from Field `Review`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Review`.`sessionId` of type `UUID!`
  """
  sessionId: UUID_Filter
  """
  ✨ Generated from Field `Review`.`studentId` of type `UUID!`
  """
  studentId: UUID_Filter
  """
  ✨ Generated from Field `Review`.`tutorId` of type `UUID!`
  """
  tutorId: UUID_Filter
  """
  ✨ Generated from Field `Review`.`session` of type `Session!`
  """
  session: Session_Filter
  """
  ✨ Generated from Field `Review`.`student` of type `User!`
  """
  student: User_Filter
  """
  ✨ Generated from Field `Review`.`tutor` of type `User!`
  """
  tutor: User_Filter
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: Int_Filter
  """
  ✨ Generated from Field `Review`.`reviewText` of type `String!`
  """
  reviewText: String_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`
  """
  updatedAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Review'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Review_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Review_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Review_Filter
}
"""
✨ Generated having input type for table 'Review'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Review_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Review_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Review_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Review_Having!]
  """
  ✨ Generated from Field `Review`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_count` of type `Int!`
  """
  rating_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`reviewText_count` of type `Int!`
  """
  reviewText_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`sessionId_count` of type `Int!`
  """
  sessionId_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`studentId_count` of type `Int!`
  """
  studentId_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`tutorId_count` of type `Int!`
  """
  tutorId_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_sum` of type `Int`
  """
  rating_sum: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_avg` of type `Float`
  """
  rating_avg: Float_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating_min` of type `Int`
  """
  rating_min: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating_max` of type `Int`
  """
  rating_max: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Review'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Review_Key {
  """
  ✨ Generated from Field `Review`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Review`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Review'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Review_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Review_Filter
}
"""
✨ Generated order input type for table 'Review'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Review_Order {
  """
  ✨ Generated from Field `Review`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Review`.`sessionId` of type `UUID!`
  """
  sessionId: OrderDirection
  """
  ✨ Generated from Field `Review`.`studentId` of type `UUID!`
  """
  studentId: OrderDirection
  """
  ✨ Generated from Field `Review`.`tutorId` of type `UUID!`
  """
  tutorId: OrderDirection
  """
  ✨ Generated from Field `Review`.`session` of type `Session!`
  """
  session: Session_Order
  """
  ✨ Generated from Field `Review`.`student` of type `User!`
  """
  student: User_Order
  """
  ✨ Generated from Field `Review`.`tutor` of type `User!`
  """
  tutor: User_Order
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: OrderDirection
  """
  ✨ Generated from Field `Review`.`reviewText` of type `String!`
  """
  reviewText: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Review`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_count` of type `Int!`
  """
  rating_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`reviewText_count` of type `Int!`
  """
  reviewText_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`sessionId_count` of type `Int!`
  """
  sessionId_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`studentId_count` of type `Int!`
  """
  studentId_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`tutorId_count` of type `Int!`
  """
  tutorId_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_sum` of type `Int`
  """
  rating_sum: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_avg` of type `Float`
  """
  rating_avg: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_min` of type `Int`
  """
  rating_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_max` of type `Int`
  """
  rating_max: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Session'. It includes all necessary fields for creating or upserting rows into table.
"""
input Session_Data {
  """
  ✨ Generated from Field `Session`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Session`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Session`.`studentId` of type `UUID!`
  """
  studentId: UUID
  """
  ✨ `_expr` server value variant of `studentId` (✨ Generated from Field `Session`.`studentId` of type `UUID!`)
  """
  studentId_expr: UUID_Expr
  """
  ✨ Generated from Field `Session`.`subjectId` of type `UUID!`
  """
  subjectId: UUID
  """
  ✨ `_expr` server value variant of `subjectId` (✨ Generated from Field `Session`.`subjectId` of type `UUID!`)
  """
  subjectId_expr: UUID_Expr
  """
  ✨ Generated from Field `Session`.`tutorId` of type `UUID!`
  """
  tutorId: UUID
  """
  ✨ `_expr` server value variant of `tutorId` (✨ Generated from Field `Session`.`tutorId` of type `UUID!`)
  """
  tutorId_expr: UUID_Expr
  """
  ✨ Generated from Field `Session`.`student` of type `User!`
  """
  student: User_Key
  """
  ✨ Generated from Field `Session`.`subject` of type `Subject!`
  """
  subject: Subject_Key
  """
  ✨ Generated from Field `Session`.`tutor` of type `User!`
  """
  tutor: User_Key
  """
  ✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Session`.`durationMinutes` of type `Int!`
  """
  durationMinutes: Int
  """
  ✨ `_expr` server value variant of `durationMinutes` (✨ Generated from Field `Session`.`durationMinutes` of type `Int!`)
  """
  durationMinutes_expr: Int_Expr
  """
  ✨ `_update` server value variant of `durationMinutes` (✨ Generated from Field `Session`.`durationMinutes` of type `Int!`)
  """
  durationMinutes_update: [Int_Update!]
  """
  ✨ Generated from Field `Session`.`notes` of type `String`
  """
  notes: String
  """
  ✨ `_expr` server value variant of `notes` (✨ Generated from Field `Session`.`notes` of type `String`)
  """
  notes_expr: String_Expr
  """
  ✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`
  """
  sessionDateTime: Timestamp
  """
  ✨ `_expr` server value variant of `sessionDateTime` (✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`)
  """
  sessionDateTime_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `sessionDateTime` (✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`)
  """
  sessionDateTime_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `sessionDateTime` (✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`)
  """
  sessionDateTime_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Session`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Session`.`status` of type `String!`)
  """
  status_expr: String_Expr
  """
  ✨ Generated from Field `Session`.`studentFeedback` of type `String`
  """
  studentFeedback: String
  """
  ✨ `_expr` server value variant of `studentFeedback` (✨ Generated from Field `Session`.`studentFeedback` of type `String`)
  """
  studentFeedback_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Session'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Session_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Session_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Session_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Session_Filter!]
  """
  ✨ Generated from Field `Session`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Session`.`studentId` of type `UUID!`
  """
  studentId: UUID_Filter
  """
  ✨ Generated from Field `Session`.`subjectId` of type `UUID!`
  """
  subjectId: UUID_Filter
  """
  ✨ Generated from Field `Session`.`tutorId` of type `UUID!`
  """
  tutorId: UUID_Filter
  """
  ✨ Generated from Field `Session`.`student` of type `User!`
  """
  student: User_Filter
  """
  ✨ Generated from Field `Session`.`subject` of type `Subject!`
  """
  subject: Subject_Filter
  """
  ✨ Generated from Field `Session`.`tutor` of type `User!`
  """
  tutor: User_Filter
  """
  ✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes` of type `Int!`
  """
  durationMinutes: Int_Filter
  """
  ✨ Generated from Field `Session`.`notes` of type `String`
  """
  notes: String_Filter
  """
  ✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`
  """
  sessionDateTime: Timestamp_Filter
  """
  ✨ Generated from Field `Session`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Session`.`studentFeedback` of type `String`
  """
  studentFeedback: String_Filter
  """
  ✨ Generated from Field `Session`.`reviews_on_session` of type `[Review!]!`
  """
  reviews_on_session: Review_ListFilter
}
"""
✨ Generated first-row input type for table 'Session'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Session_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Session_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Session_Filter
}
"""
✨ Generated having input type for table 'Session'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Session_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Session_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Session_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Session_Having!]
  """
  ✨ Generated from Field `Session`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Session`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes_count` of type `Int!`
  """
  durationMinutes_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`notes_count` of type `Int!`
  """
  notes_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`sessionDateTime_count` of type `Int!`
  """
  sessionDateTime_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`studentFeedback_count` of type `Int!`
  """
  studentFeedback_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`studentId_count` of type `Int!`
  """
  studentId_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`subjectId_count` of type `Int!`
  """
  subjectId_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`tutorId_count` of type `Int!`
  """
  tutorId_count: Int_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes_sum` of type `Int`
  """
  durationMinutes_sum: Int_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes_avg` of type `Float`
  """
  durationMinutes_avg: Float_Filter
  """
  ✨ Generated from Field `Session`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes_min` of type `Int`
  """
  durationMinutes_min: Int_Filter
  """
  ✨ Generated from Field `Session`.`sessionDateTime_min` of type `Timestamp`
  """
  sessionDateTime_min: Timestamp_Filter
  """
  ✨ Generated from Field `Session`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Session`.`durationMinutes_max` of type `Int`
  """
  durationMinutes_max: Int_Filter
  """
  ✨ Generated from Field `Session`.`sessionDateTime_max` of type `Timestamp`
  """
  sessionDateTime_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Session'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Session_Key {
  """
  ✨ Generated from Field `Session`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Session`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Session'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Session_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Session_Filter
}
"""
✨ Generated order input type for table 'Session'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Session_Order {
  """
  ✨ Generated from Field `Session`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Session`.`studentId` of type `UUID!`
  """
  studentId: OrderDirection
  """
  ✨ Generated from Field `Session`.`subjectId` of type `UUID!`
  """
  subjectId: OrderDirection
  """
  ✨ Generated from Field `Session`.`tutorId` of type `UUID!`
  """
  tutorId: OrderDirection
  """
  ✨ Generated from Field `Session`.`student` of type `User!`
  """
  student: User_Order
  """
  ✨ Generated from Field `Session`.`subject` of type `Subject!`
  """
  subject: Subject_Order
  """
  ✨ Generated from Field `Session`.`tutor` of type `User!`
  """
  tutor: User_Order
  """
  ✨ Generated from Field `Session`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes` of type `Int!`
  """
  durationMinutes: OrderDirection
  """
  ✨ Generated from Field `Session`.`notes` of type `String`
  """
  notes: OrderDirection
  """
  ✨ Generated from Field `Session`.`sessionDateTime` of type `Timestamp!`
  """
  sessionDateTime: OrderDirection
  """
  ✨ Generated from Field `Session`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Session`.`studentFeedback` of type `String`
  """
  studentFeedback: OrderDirection
  """
  ✨ Generated from Field `Session`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Session`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes_count` of type `Int!`
  """
  durationMinutes_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`notes_count` of type `Int!`
  """
  notes_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`sessionDateTime_count` of type `Int!`
  """
  sessionDateTime_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`studentFeedback_count` of type `Int!`
  """
  studentFeedback_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`studentId_count` of type `Int!`
  """
  studentId_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`subjectId_count` of type `Int!`
  """
  subjectId_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`tutorId_count` of type `Int!`
  """
  tutorId_count: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes_sum` of type `Int`
  """
  durationMinutes_sum: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes_avg` of type `Float`
  """
  durationMinutes_avg: OrderDirection
  """
  ✨ Generated from Field `Session`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes_min` of type `Int`
  """
  durationMinutes_min: OrderDirection
  """
  ✨ Generated from Field `Session`.`sessionDateTime_min` of type `Timestamp`
  """
  sessionDateTime_min: OrderDirection
  """
  ✨ Generated from Field `Session`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Session`.`durationMinutes_max` of type `Int`
  """
  durationMinutes_max: OrderDirection
  """
  ✨ Generated from Field `Session`.`sessionDateTime_max` of type `Timestamp`
  """
  sessionDateTime_max: OrderDirection
}
"""
✨ Generated data input type for table 'Subject'. It includes all necessary fields for creating or upserting rows into table.
"""
input Subject_Data {
  """
  ✨ Generated from Field `Subject`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Subject`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Subject`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Subject`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Subject`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Subject`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Subject'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Subject_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Subject_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Subject_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Subject_Filter!]
  """
  ✨ Generated from Field `Subject`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Subject`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Subject`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Subject`.`resources_on_subject` of type `[Resource!]!`
  """
  resources_on_subject: Resource_ListFilter
  """
  ✨ Generated from Field `Subject`.`sessions_on_subject` of type `[Session!]!`
  """
  sessions_on_subject: Session_ListFilter
  """
  ✨ Generated from Field `Subject`.`tutorSubjects_on_subject` of type `[TutorSubject!]!`
  """
  tutorSubjects_on_subject: TutorSubject_ListFilter
  """
  ✨ Generated from Field `Subject`.`tutorProfiles_via_TutorSubject` of type `[TutorProfile!]!`
  """
  tutorProfiles_via_TutorSubject: TutorProfile_ListFilter
}
"""
✨ Generated first-row input type for table 'Subject'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Subject_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Subject_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Subject_Filter
}
"""
✨ Generated having input type for table 'Subject'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Subject_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Subject_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Subject_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Subject_Having!]
  """
  ✨ Generated from Field `Subject`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Subject`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Subject`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Subject`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Subject`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Subject`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Subject`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Subject'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Subject_Key {
  """
  ✨ Generated from Field `Subject`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Subject`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Subject'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Subject_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Subject_Filter
}
"""
✨ Generated order input type for table 'Subject'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Subject_Order {
  """
  ✨ Generated from Field `Subject`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Subject`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Subject`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Subject`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Subject`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Subject`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Subject`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Subject`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Subject`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Subject`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Subject`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'TutorProfile'. It includes all necessary fields for creating or upserting rows into table.
"""
input TutorProfile_Data {
  """
  ✨ Generated from Field `TutorProfile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TutorProfile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `TutorProfile`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `TutorProfile`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr
  """
  ✨ Generated from Field `TutorProfile`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `TutorProfile`.`averageRating` of type `Float`
  """
  averageRating: Float
  """
  ✨ `_expr` server value variant of `averageRating` (✨ Generated from Field `TutorProfile`.`averageRating` of type `Float`)
  """
  averageRating_expr: Float_Expr
  """
  ✨ `_update` server value variant of `averageRating` (✨ Generated from Field `TutorProfile`.`averageRating` of type `Float`)
  """
  averageRating_update: [Float_Update!]
  """
  ✨ Generated from Field `TutorProfile`.`bio` of type `String!`
  """
  bio: String
  """
  ✨ `_expr` server value variant of `bio` (✨ Generated from Field `TutorProfile`.`bio` of type `String!`)
  """
  bio_expr: String_Expr
  """
  ✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears` of type `Int`
  """
  experienceYears: Int
  """
  ✨ `_expr` server value variant of `experienceYears` (✨ Generated from Field `TutorProfile`.`experienceYears` of type `Int`)
  """
  experienceYears_expr: Int_Expr
  """
  ✨ `_update` server value variant of `experienceYears` (✨ Generated from Field `TutorProfile`.`experienceYears` of type `Int`)
  """
  experienceYears_update: [Int_Update!]
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate` of type `Float!`
  """
  hourlyRate: Float
  """
  ✨ `_expr` server value variant of `hourlyRate` (✨ Generated from Field `TutorProfile`.`hourlyRate` of type `Float!`)
  """
  hourlyRate_expr: Float_Expr
  """
  ✨ `_update` server value variant of `hourlyRate` (✨ Generated from Field `TutorProfile`.`hourlyRate` of type `Float!`)
  """
  hourlyRate_update: [Float_Update!]
  """
  ✨ Generated from Field `TutorProfile`.`qualifications` of type `String`
  """
  qualifications: String
  """
  ✨ `_expr` server value variant of `qualifications` (✨ Generated from Field `TutorProfile`.`qualifications` of type `String`)
  """
  qualifications_expr: String_Expr
}
"""
✨ Generated filter input type for table 'TutorProfile'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TutorProfile_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [TutorProfile_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: TutorProfile_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [TutorProfile_Filter!]
  """
  ✨ Generated from Field `TutorProfile`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `TutorProfile`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `TutorProfile`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating` of type `Float`
  """
  averageRating: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`bio` of type `String!`
  """
  bio: String_Filter
  """
  ✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears` of type `Int`
  """
  experienceYears: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate` of type `Float!`
  """
  hourlyRate: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`qualifications` of type `String`
  """
  qualifications: String_Filter
  """
  ✨ Generated from Field `TutorProfile`.`tutorSubjects_on_tutorProfile` of type `[TutorSubject!]!`
  """
  tutorSubjects_on_tutorProfile: TutorSubject_ListFilter
  """
  ✨ Generated from Field `TutorProfile`.`subjects_via_TutorSubject` of type `[Subject!]!`
  """
  subjects_via_TutorSubject: Subject_ListFilter
}
"""
✨ Generated first-row input type for table 'TutorProfile'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input TutorProfile_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [TutorProfile_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: TutorProfile_Filter
}
"""
✨ Generated having input type for table 'TutorProfile'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TutorProfile_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [TutorProfile_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: TutorProfile_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [TutorProfile_Having!]
  """
  ✨ Generated from Field `TutorProfile`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_count` of type `Int!`
  """
  averageRating_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`bio_count` of type `Int!`
  """
  bio_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_count` of type `Int!`
  """
  experienceYears_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_count` of type `Int!`
  """
  hourlyRate_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`qualifications_count` of type `Int!`
  """
  qualifications_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_sum` of type `Float`
  """
  averageRating_sum: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_sum` of type `Int`
  """
  experienceYears_sum: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_sum` of type `Float`
  """
  hourlyRate_sum: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_avg` of type `Float`
  """
  averageRating_avg: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_avg` of type `Float`
  """
  experienceYears_avg: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_avg` of type `Float`
  """
  hourlyRate_avg: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_min` of type `Float`
  """
  averageRating_min: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_min` of type `Int`
  """
  experienceYears_min: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_min` of type `Float`
  """
  hourlyRate_min: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_max` of type `Float`
  """
  averageRating_max: Float_Filter
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_max` of type `Int`
  """
  experienceYears_max: Int_Filter
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_max` of type `Float`
  """
  hourlyRate_max: Float_Filter
}
"""
✨ Generated key input type for table 'TutorProfile'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input TutorProfile_Key {
  """
  ✨ Generated from Field `TutorProfile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TutorProfile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'TutorProfile'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input TutorProfile_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: TutorProfile_Filter
}
"""
✨ Generated order input type for table 'TutorProfile'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input TutorProfile_Order {
  """
  ✨ Generated from Field `TutorProfile`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `TutorProfile`.`averageRating` of type `Float`
  """
  averageRating: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`bio` of type `String!`
  """
  bio: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears` of type `Int`
  """
  experienceYears: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate` of type `Float!`
  """
  hourlyRate: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`qualifications` of type `String`
  """
  qualifications: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_count` of type `Int!`
  """
  averageRating_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`bio_count` of type `Int!`
  """
  bio_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_count` of type `Int!`
  """
  experienceYears_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_count` of type `Int!`
  """
  hourlyRate_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`qualifications_count` of type `Int!`
  """
  qualifications_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_sum` of type `Float`
  """
  averageRating_sum: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_sum` of type `Int`
  """
  experienceYears_sum: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_sum` of type `Float`
  """
  hourlyRate_sum: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_avg` of type `Float`
  """
  averageRating_avg: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_avg` of type `Float`
  """
  experienceYears_avg: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_avg` of type `Float`
  """
  hourlyRate_avg: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_min` of type `Float`
  """
  averageRating_min: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_min` of type `Int`
  """
  experienceYears_min: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_min` of type `Float`
  """
  hourlyRate_min: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`averageRating_max` of type `Float`
  """
  averageRating_max: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`experienceYears_max` of type `Int`
  """
  experienceYears_max: OrderDirection
  """
  ✨ Generated from Field `TutorProfile`.`hourlyRate_max` of type `Float`
  """
  hourlyRate_max: OrderDirection
}
"""
✨ Generated data input type for table 'TutorSubject'. It includes all necessary fields for creating or upserting rows into table.
"""
input TutorSubject_Data {
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`
  """
  tutorProfileId: UUID
  """
  ✨ `_expr` server value variant of `tutorProfileId` (✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`)
  """
  tutorProfileId_expr: UUID_Expr
  """
  ✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`
  """
  subjectId: UUID
  """
  ✨ `_expr` server value variant of `subjectId` (✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`)
  """
  subjectId_expr: UUID_Expr
  """
  ✨ Generated from Field `TutorSubject`.`subject` of type `Subject!`
  """
  subject: Subject_Key
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfile` of type `TutorProfile!`
  """
  tutorProfile: TutorProfile_Key
  """
  ✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'TutorSubject'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TutorSubject_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [TutorSubject_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: TutorSubject_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [TutorSubject_Filter!]
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`
  """
  tutorProfileId: UUID_Filter
  """
  ✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`
  """
  subjectId: UUID_Filter
  """
  ✨ Generated from Field `TutorSubject`.`subject` of type `Subject!`
  """
  subject: Subject_Filter
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfile` of type `TutorProfile!`
  """
  tutorProfile: TutorProfile_Filter
  """
  ✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'TutorSubject'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input TutorSubject_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [TutorSubject_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: TutorSubject_Filter
}
"""
✨ Generated having input type for table 'TutorSubject'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TutorSubject_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [TutorSubject_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: TutorSubject_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [TutorSubject_Having!]
  """
  ✨ Generated from Field `TutorSubject`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `TutorSubject`.`subjectId_count` of type `Int!`
  """
  subjectId_count: Int_Filter
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId_count` of type `Int!`
  """
  tutorProfileId_count: Int_Filter
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'TutorSubject'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input TutorSubject_Key {
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`
  """
  tutorProfileId: UUID
  """
  ✨ `_expr` server value variant of `tutorProfileId` (✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`)
  """
  tutorProfileId_expr: UUID_Expr
  """
  ✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`
  """
  subjectId: UUID
  """
  ✨ `_expr` server value variant of `subjectId` (✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`)
  """
  subjectId_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'TutorSubject'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input TutorSubject_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: TutorSubject_Filter
}
"""
✨ Generated order input type for table 'TutorSubject'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input TutorSubject_Order {
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId` of type `UUID!`
  """
  tutorProfileId: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`subjectId` of type `UUID!`
  """
  subjectId: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`subject` of type `Subject!`
  """
  subject: Subject_Order
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfile` of type `TutorProfile!`
  """
  tutorProfile: TutorProfile_Order
  """
  ✨ Generated from Field `TutorSubject`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`subjectId_count` of type `Int!`
  """
  subjectId_count: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`tutorProfileId_count` of type `Int!`
  """
  tutorProfileId_count: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `TutorSubject`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: String
  """
  ✨ `_expr` server value variant of `bio` (✨ Generated from Field `User`.`bio` of type `String`)
  """
  bio_expr: String_Expr
  """
  ✨ Generated from Field `User`.`contactInfo` of type `String`
  """
  contactInfo: String
  """
  ✨ `_expr` server value variant of `contactInfo` (✨ Generated from Field `User`.`contactInfo` of type `String`)
  """
  contactInfo_expr: String_Expr
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String!`)
  """
  displayName_expr: String_Expr
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr
  """
  ✨ Generated from Field `User`.`userType` of type `String!`
  """
  userType: String
  """
  ✨ `_expr` server value variant of `userType` (✨ Generated from Field `User`.`userType` of type `String!`)
  """
  userType_expr: String_Expr
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: String_Filter
  """
  ✨ Generated from Field `User`.`contactInfo` of type `String`
  """
  contactInfo: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`userType` of type `String!`
  """
  userType: String_Filter
  """
  ✨ Generated from Field `User`.`resources_on_uploader` of type `[Resource!]!`
  """
  resources_on_uploader: Resource_ListFilter
  """
  ✨ Generated from Field `User`.`reviews_on_student` of type `[Review!]!`
  """
  reviews_on_student: Review_ListFilter
  """
  ✨ Generated from Field `User`.`reviews_on_tutor` of type `[Review!]!`
  """
  reviews_on_tutor: Review_ListFilter
  """
  ✨ Generated from Field `User`.`sessions_on_student` of type `[Session!]!`
  """
  sessions_on_student: Session_ListFilter
  """
  ✨ Generated from Field `User`.`sessions_on_tutor` of type `[Session!]!`
  """
  sessions_on_tutor: Session_ListFilter
  """
  ✨ Generated from Field `User`.`tutorProfiles_on_user` of type `[TutorProfile!]!`
  """
  tutorProfiles_on_user: TutorProfile_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`bio_count` of type `Int!`
  """
  bio_count: Int_Filter
  """
  ✨ Generated from Field `User`.`contactInfo_count` of type `Int!`
  """
  contactInfo_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: Int_Filter
  """
  ✨ Generated from Field `User`.`userType_count` of type `Int!`
  """
  userType_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: OrderDirection
  """
  ✨ Generated from Field `User`.`contactInfo` of type `String`
  """
  contactInfo: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`userType` of type `String!`
  """
  userType: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`bio_count` of type `Int!`
  """
  bio_count: OrderDirection
  """
  ✨ Generated from Field `User`.`contactInfo_count` of type `Int!`
  """
  contactInfo_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: OrderDirection
  """
  ✨ Generated from Field `User`.`userType_count` of type `Int!`
  """
  userType_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
